// Copyright 2026 bong-water-water-bong
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// text_stream.h: turns per-token bytes into text deltas that are safe to send.
//
// Three stages, applied in order to the generated bytes:
//   1. UTF-8: a token can end inside a multi-byte character; those bytes wait
//      for the rest of the character.
//   2. Stop strings: text that could be the start of a stop string waits until
//      it either completes the stop string (generation ends, the stop string is
//      not emitted) or cannot.
//   3. Reasoning: with split_reasoning, a leading <think>...</think> block goes
//      to `reasoning` and the rest to `content` (llama-server's reasoning
//      format), with the whitespace around the block trimmed.
#pragma once

#include <string>
#include <string_view>
#include <vector>

namespace onebit {

struct TextDelta {
    std::string content;
    std::string reasoning;
    bool empty() const { return content.empty() && reasoning.empty(); }
};

class TextStream {
public:
    // reasoning_open: the prompt already opened a <think> block, so output
    // starts inside it (templates that end the prompt with "<think>\n").
    TextStream(std::vector<std::string> stops, bool split_reasoning, bool reasoning_open = false);

    // Feeds the bytes of one generated token. Returns what can be sent now.
    TextDelta push(std::string_view bytes);

    // True once a stop string has matched; later pushes return nothing.
    bool stopped() const { return stopped_; }

    // End of generation: releases held text (an incomplete UTF-8 tail is dropped).
    TextDelta finish();

    // Everything emitted so far.
    const std::string& content() const { return all_content_; }
    const std::string& reasoning() const { return all_reasoning_; }

private:
    void route(std::string_view text, bool final, TextDelta& out);
    void emit(TextDelta& out, std::string_view content, std::string_view reasoning);

    std::vector<std::string> stops_;
    bool split_;
    enum class Mode { Start, Reasoning, Content } mode_;
    bool trim_content_start_ = false;
    bool stopped_ = false;
    std::string utf8_tail_;  // incomplete UTF-8 sequence
    std::string stop_hold_;  // text that may begin a stop string
    std::string route_hold_; // text held by the reasoning router
    std::string all_content_, all_reasoning_;
};

}  // namespace onebit
