#!/usr/bin/env python3
"""Generate engine/core/unicode_tables.inc from Python's unicodedata.

usage: python3 tools/gen_unicode_tables.py > engine/core/unicode_tables.inc

Tables:
  kLetterRanges / kNumberRanges  general categories L* / N* as [lo, hi] ranges
  kCccRanges                     canonical combining class, [lo, hi, ccc], ccc != 0
  kDecomp / kDecompData          full canonical decomposition (Hangul excluded: algorithmic)
  kCompose                       primary composites: (first << 21 | second) -> composite
"""
import sys
import unicodedata

MAX = 0x110000
HANGUL = range(0xAC00, 0xAC00 + 11172)


def ranges(pred):
    out, start = [], None
    for cp in range(MAX):
        if pred(cp):
            if start is None:
                start = cp
        elif start is not None:
            out.append((start, cp - 1))
            start = None
    if start is not None:
        out.append((start, MAX - 1))
    return out


def full_decomp(cp):
    d = unicodedata.decomposition(chr(cp))
    if not d or d.startswith("<"):
        return [cp]
    out = []
    for part in d.split():
        out.extend(full_decomp(int(part, 16)))
    return out


def main():
    w = sys.stdout.write
    w("// Generated by tools/gen_unicode_tables.py from Python unicodedata %s. Do not edit.\n"
      % unicodedata.unidata_version)
    w("// clang-format off\n")

    for name, cats in (("kLetterRanges", "L"), ("kNumberRanges", "N")):
        rs = ranges(lambda cp: unicodedata.category(chr(cp))[0] == cats)
        w("constexpr uint32_t %s[][2] = {\n" % name)
        for lo, hi in rs:
            w("    {0x%X, 0x%X},\n" % (lo, hi))
        w("};\n")

    ccc = []
    cur = None
    for cp in range(MAX):
        c = unicodedata.combining(chr(cp))
        if cur and c == cur[2] and cp == cur[1] + 1:
            cur[1] = cp
            continue
        if cur:
            ccc.append(cur)
        cur = [cp, cp, c] if c else None
    if cur:
        ccc.append(cur)
    w("constexpr uint32_t kCccRanges[][3] = {\n")
    for lo, hi, c in ccc:
        w("    {0x%X, 0x%X, %d},\n" % (lo, hi, c))
    w("};\n")

    decomp, data = [], []
    compose = []
    for cp in range(MAX):
        if cp in HANGUL:
            continue
        d = full_decomp(cp)
        if d != [cp]:
            decomp.append((cp, len(data), len(d)))
            data.extend(d)
        raw = unicodedata.decomposition(chr(cp))
        if raw and not raw.startswith("<"):
            parts = [int(p, 16) for p in raw.split()]
            # Primary composite: NFC of its own decomposition gives it back.
            if len(parts) == 2 and unicodedata.normalize("NFC", chr(parts[0]) + chr(parts[1])) == chr(cp):
                compose.append(((parts[0] << 21) | parts[1], cp))
    w("struct DecompEntry { uint32_t cp; uint16_t offset; uint8_t len; };\n")
    w("constexpr DecompEntry kDecomp[] = {\n")
    for cp, off, n in decomp:
        w("    {0x%X, %d, %d},\n" % (cp, off, n))
    w("};\n")
    w("constexpr uint32_t kDecompData[] = {\n")
    for i in range(0, len(data), 12):
        w("    " + ", ".join("0x%X" % x for x in data[i:i + 12]) + ",\n")
    w("};\n")
    compose.sort()
    w("struct ComposeEntry { uint64_t key; uint32_t composite; };\n")
    w("constexpr ComposeEntry kCompose[] = {\n")
    for key, cp in compose:
        w("    {0x%XULL, 0x%X},\n" % (key, cp))
    w("};\n")
    w("// clang-format on\n")


if __name__ == "__main__":
    main()
