// Copyright 2026 bong-water-water-bong
// SPDX-License-Identifier: Apache-2.0
//
// Licensed under the Apache License, Version 2.0 (the "License");
// you may not use this file except in compliance with the License.
// You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.
// Copyright (c) 2026 bong-water-water-bong
#ifndef NPU_INFER_COMMON_H
#define NPU_INFER_COMMON_H

#include <stdint.h>
#include <stddef.h>
#include <stdbool.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>

#define NPU_MAX_CTX 16

// Model configuration for Qwen3-0.6B (NPU-verified values)
typedef struct {
    int32_t hidden_size;
    int32_t num_layers;
    int32_t num_attention_heads;
    int32_t num_key_value_heads;
    int32_t intermediate_size;
    int32_t head_dim;
    int32_t vocab_size;
    int32_t max_position_embeddings;
    int32_t max_seq_len;
    float rms_norm_eps;
    bool tie_word_embeddings;
    
    // NPU-specific blocked format constants
    uint32_t npu_block_cols;   // 1024 — each BO holds this many columns
    uint32_t npu_block_rows;   // 256 — each BO holds this many rows
    uint32_t npu_weight_bo_size; // 1048576 — 1MB per weight BO
    uint32_t npu_activation_bo_size; // 1048576 — 1MB per activation BO
    uint32_t npu_kv_cache_bo_size; // 134217728 — 128MB per KV cache BO (UNIT: allocation,
                                   // a capacity CEILING. It is deliberately larger than the
                                   // layout below needs; do not read it as a token count.)
} ModelConfig;

static const ModelConfig QWEN3_0_6B_CONFIG = {
    .hidden_size = 1024,
    .num_layers = 28,
    .num_attention_heads = 16,
    .num_key_value_heads = 8,
    .intermediate_size = 3072,
    .head_dim = 128,
    .vocab_size = 151936,
    .max_position_embeddings = 40960,
    .max_seq_len = 4096,
    .rms_norm_eps = 1e-6f,
    .tie_word_embeddings = true,
    // NPU blocked format
    .npu_block_cols = 1024,
    .npu_block_rows = 256,
    .npu_weight_bo_size = 1048576,
    .npu_activation_bo_size = 1048576,
    .npu_kv_cache_bo_size = 134217728,
};

// XCLBIN types
typedef enum {
    XCLBIN_MM = 0,       // GEMM operations
    XCLBIN_ATTN,         // Attention
    XCLBIN_LAYER,        // Full layer
    XCLBIN_DEQUANT,      // Dequantization
    XCLBIN_COUNT
} XclbinType;

static const char* XCLBIN_NAMES[XCLBIN_COUNT] = {
    "mm.xclbin",
    "attn.xclbin",
    "layer.xclbin",
    "dequant.xclbin"
};

// Override with NPU_XCLBIN_DIR=/path/to/xclbins to point at another model's
// xclbin set (each dir must contain mm/attn/layer/dequant .xclbin + .bin insts).
// The insts file for <name>.xclbin is <name>.bin in the same directory,
// generated by tools/gen_mm_insts (FastFlowLM Gemm::generate_seq).
static const char* XCLBIN_PATHS[XCLBIN_COUNT] = {
    "/home/bcloud/amd-oss/fastflowlm/src/xclbins/Qwen3-0.6B-NPU2/mm.xclbin",
    "/home/bcloud/amd-oss/fastflowlm/src/xclbins/Qwen3-0.6B-NPU2/attn.xclbin",
    "/home/bcloud/amd-oss/fastflowlm/src/xclbins/Qwen3-0.6B-NPU2/layer.xclbin",
    "/home/bcloud/amd-oss/fastflowlm/src/xclbins/Qwen3-0.6B-NPU2/dequant.xclbin",
};

// Full-ELF equivalents (aiecc --generate-full-elf). A full ELF is a drop-in
// xclbin replacement: XRT builds the hw_context from it (xrt::elf ->
// xrt::hw_context(device, elf) -> xrt::ext::kernel) with no xclbin at all.
// Resolved against NPU_INFER_ELF_DIR (default engine/npu/xclbins). Only used
// when NPU_INFER_ELF=1; the xclbin path stays the default for A/B comparison.
static const char* XCLBIN_ELF_NAMES[XCLBIN_COUNT] = {
    "full_i8_QKV_qwen3_0_6b.elf",  // MM   — Qwen3-0.6B QKV GEMM, 3 BO args (A,B,C)
    "full_attn.elf",                // ATTN — GQA attention, 5 BO args
    "full_i8_O_qwen3_0_6b.elf",     // LAYER   (unused by this engine)
    "full_i8_GU_qwen3_0_6b.elf"     // DEQUANT (unused by this engine)
};

// BO arity of each full-ELF kernel above. The system XRT (2.21.75) xrt::elf has
// no get_kernels(), so the arity is declared here (it is fixed by the design):
// the full-ELF kernel takes only the data BOs — the xclbin kernel's
// (opcode, instr, ninstr) prefix is gone because the instruction stream is
// embedded in the ELF.
static const int XCLBIN_ELF_ARGS[XCLBIN_COUNT] = { 3, 5, 3, 3 };

// NPU kernel argument indices
typedef enum {
    KERN_ARG_OPCODE = 0,    // uint32_t
    KERN_ARG_INSTR_PTR,     // uint64_t: insts BO (REQUIRED — see XclbinManager)
    KERN_ARG_NINSTR,        // uint32_t: insts count in words (REQUIRED)
    KERN_ARG_ACTIVATION,    // idx=3: shared activation buffer (1MB)
    KERN_ARG_ACT_WORKSPACE, // idx=4: activation workspace (10MB)
    KERN_ARG_WEIGHT1,       // idx=5: weight buffer #1 (1MB)
    KERN_ARG_WEIGHT2,       // idx=6: weight buffer #2 (1MB)
    KERN_ARG_KVCACHE,       // idx=7: KV cache (128MB)
    KERN_ARG_COUNT
} KernelArgIndex;

#define OPCODE_GEMM  3  // mm.xclbin GEMM kernel
#define OPCODE_ATTN  4  // attn.xclbin attention kernel (example)
#define OPCODE_LAYER 5  // layer.xclbin layer kernel
#define OPCODE_DEQUANT 2 // dequant.xclbin dequant kernel

// Block quantization constants for Q4NX format
#define GROUP_SIZE 32
#define MAX_GROUPS 32768

// Logging
#define LOG_INFO(fmt, ...)  fprintf(stderr, "[INFO]  " fmt "\n", ##__VA_ARGS__)
#define LOG_ERROR(fmt, ...) fprintf(stderr, "[ERROR] " fmt "\n", ##__VA_ARGS__)
#define LOG_DEBUG(fmt, ...) fprintf(stderr, "[DEBUG] " fmt "\n", ##__VA_ARGS__)
#define LOG_WARNING(fmt, ...) fprintf(stderr, "[WARN]  " fmt "\n", ##__VA_ARGS__)

#endif // NPU_INFER_COMMON_H
